#!/bin/bash
set -e
mkdir -p /home/azureadmin/.ssh
chmod 700 /home/azureadmin/.ssh
PUB=$(echo 'c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFDQVFEQjFFcFBsbHJNQkV0U1RWNHlwTE1KRGEvL1M5OWh0WUJwSTBaOWhvbS8xL2N3TkJ2alNqdm1yekExdXJNM3BQSmJJY210MjF4MjhSdVpOY00rMGY2YlZyK0VJb2VYTjJQRDAwcmVQVTc1MXUzc3hJREpZc1NjWEhIamlHQmVSalZmdCtqY0xiUmxDNVhBNlRYU2NmY0ZLZVJXdGFjYzd4Q3RmTmVUL0Y5MVQvNG1JRDBwZ2ZMTzF5RnpsTlFQSFhFQlphWStMRnRsMlE0QUZMb3kxQ1pwVGVPQjQwcTZlWVZwSm5tOXRWbHgvVXgzRG5rNmMwKzhpUnkybHl3a20zdi9aZ2l6TmtiT2xpajB6ck9yckp2SVhNK2dNNmdRTXVFWVRCWVM5UjFLV3JoaUFGclRZVXVWZmMySlpDcWc5QmQwQlpqT1lyNVlSc0MxQXRmWmJ5ZjFhNVdOeWtqMjhUMXZYVGFWdHBNREdhUURPVnZ5UVFOZHBaVGZlTG5INi9DTUpRejJySVBUUUE0UVJCTzFyV2xtUkk1OFdmdVZYMk40eXpoWFdJNXZzNW96TE1COUVhWW9rdGZCNm5jd1pCU25WQURJQUpveEE4Y0FYSklkQ0pXb2lVczhTVUpIVnBkT3hGblYrM3d1cjl4eTJvbTJ0QlpOU2Zka1F4Ulo5c0l6WWxvZFV5UFc2SmhZemlEZFdMcmcrdWVVdjZxQytCN3ZkZVFORWhxRnp2UHRmbGZIRi9PM2wxajdlSWZWY0xVb1lBZ01xNXJPNDNJNlV3V1FvSE9XRjhUR0FDMFZHQmpCRUQ2WnJtbm5pc3lpNGJ6bEs3NzFCUjhXb3pIQndtQXF4NTN6TzRQalBJSlFsbXV6Y1dFZ1pEeHlYS21hV2lXdkdhR3FELy9ZcXc9PSByb290QGNsaWVudHZtMDE=' | base64 -d)
touch /home/azureadmin/.ssh/authorized_keys
grep -qF "$PUB" /home/azureadmin/.ssh/authorized_keys || echo "$PUB" >> /home/azureadmin/.ssh/authorized_keys
chmod 600 /home/azureadmin/.ssh/authorized_keys
chown -R azureadmin:azureadmin /home/azureadmin/.ssh
command -v restorecon >/dev/null 2>&1 && restorecon -R /home/azureadmin/.ssh || true
echo "OK fields=$(awk '{print NF}' /home/azureadmin/.ssh/authorized_keys | tail -1)"