brokerClusterName=RocketMQCluster
brokerName=broker-b
brokerId=0
brokerRole=SYNC_MASTER
flushDiskType=ASYNC_FLUSH
namesrvAddr=10.161.0.4:9876;10.161.0.5:9876;10.161.0.6:9876
listenPort=10911
storePathRootDir=/datadisk/rocketmq/store
storePathCommitLog=/datadisk/rocketmq/store/commitlog
storePathConsumeQueue=/datadisk/rocketmq/store/consumequeue
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
sendMessageThreadPoolNums=16
